function l(b,a,c,d,e){b.o.Gb(b.mb,a,c,d,e)}function m(b,a,c,d){b.o.ca?l(b,a,c,d):b.o.Ee()._OnMessageFromDOM({type:"event",component:b.mb,handler:a,dispatchOpts:d||null,data:c,responseId:null})}function n(b,a,c){b.o.C(b.mb,a,c)}function t(b,a){for(const [c,d]of a)n(b,c,d)}function u(b){b.Sb||(b.o.rd(b.Xd),b.Sb=!0)}function aa(b){b.Sb&&(b.o.Pe(b.Xd),b.Sb=!1)}window.Ma=class{constructor(b,a){this.o=b;this.mb=a;this.Sb=!1;this.Xd=()=>this.Ea()}gd(){}Ea(){}};
window.mf=class{constructor(){this.dd=-1}j(){-1!==this.dd&&(self.clearTimeout(this.dd),this.dd=-1)}};"use strict";class ba{constructor(b){this.Qb=b;this.Oc=!1;this.Wc=!0}}function ca(b,a){const c=a.elementId,d=b.ld(c,a),e=new ba(d);b.Ra.set(c,e);d.style.boxSizing="border-box";d.style.display="none";e.Wc=!!a.isVisible;d.addEventListener("focus",()=>{v(b,"elem-focused",c)});d.addEventListener("blur",()=>{v(b,"elem-blurred",c)});b.kb&&document.body.appendChild(d)}
function w(b,a,c){n(b,a,d=>{const e=x(b,d.elementId);return c(e,d)})}function x(b,a){b=b.Ra.get(a);if(!b)throw Error(`no element with id ${a}`);return b.Qb}function v(b,a,c,d){d||(d={});d.elementId=c;l(b,a,d)}
window.pe=class extends self.Ma{constructor(b){super(b,"video");this.Ra=new Map;this.kb=!0;t(this,[["create",a=>ca(this,a)],["destroy",a=>{a=a.elementId;const c=x(this,a);this.nd(c);this.kb&&c.parentElement.removeChild(c);this.Ra.delete(a)}],["set-visible",a=>{if(this.kb){var c=this.Ra.get(a.elementId),d=c.Qb;c.Oc?d.style.display=a.isVisible?"":"none":c.Wc=!!a.isVisible}}],["update-position",a=>{if(this.kb){var c=this.Ra.get(a.elementId),d=c.Qb;d.style.left=a.left+"px";d.style.top=a.top+"px";d.style.width=
a.width+"px";d.style.height=a.height+"px";a=a.fontSize;null!==a&&(d.style.fontSize=a+"em");c.Oc||(c.Oc=!0,c.Wc&&(d.style.display=""))}}],["update-state",a=>{x(this,a.elementId);this.qd()}],["focus",a=>this.Ec(a)],["set-css-style",a=>{const c=x(this,a.elementId),d=a.prop;a=a.val;d.startsWith("--")?c.style.setProperty(d,a):c.style[d]=a}],["set-attribute",a=>{x(this,a.elementId).setAttribute(a.name,a.val)}],["remove-attribute",a=>{x(this,a.elementId).removeAttribute(a.name)}]]);w(this,"get-element",
a=>a)}ld(){throw Error("required override");}nd(){}qd(){throw Error("required override");}Ec(b){var a=x(this,b.elementId);b.focus?a.focus():a.blur()}};"use strict";const da=/(iphone|ipod|ipad|macos|macintosh|mac os x)/i.test(navigator.userAgent),y=/android/i.test(navigator.userAgent),ea=/safari/i.test(navigator.userAgent)&&!/(chrome|chromium|edg\/|OPR\/|nwjs)/i.test(navigator.userAgent);let fa=0;
function A(b){const a=document.createElement("script");a.async=!1;a.type="module";return b.bf?new Promise(c=>{const d="c3_resolve_"+fa;++fa;self[d]=c;a.textContent=b.ff+`\n\nself["${d}"]();`;document.head.appendChild(a)}):new Promise((c,d)=>{a.onload=c;a.onerror=d;a.src=b;document.head.appendChild(a)})}let ha=!1,ia=!1;function ja(){if(!ha){try{new Worker("blob://",{get type(){ia=!0}})}catch(b){}ha=!0}return ia}let B=new Audio;
const ka={"audio/webm; codecs=opus":!!B.canPlayType("audio/webm; codecs=opus"),"audio/ogg; codecs=opus":!!B.canPlayType("audio/ogg; codecs=opus"),"audio/webm; codecs=vorbis":!!B.canPlayType("audio/webm; codecs=vorbis"),"audio/ogg; codecs=vorbis":!!B.canPlayType("audio/ogg; codecs=vorbis"),"audio/mp4":!!B.canPlayType("audio/mp4"),"audio/mpeg":!!B.canPlayType("audio/mpeg")};B=null;async function la(b){b=await ma(b);return(new TextDecoder("utf-8")).decode(b)}
function ma(b){return new Promise((a,c)=>{const d=new FileReader;d.onload=e=>a(e.target.result);d.onerror=e=>c(e);d.readAsArrayBuffer(b)})}const na=[];let E=0;window.RealFile=window.File;const F=[],ra=new Map,sa=new Map;let ta=0;const ua=[];self.runOnStartup=function(b){if("function"!==typeof b)throw Error("runOnStartup called without a function");ua.push(b)};const va=new Set(["cordova","playable-ad","instant-games"]);let wa=!1;
window.qa=class b{constructor(a){this.ca=a.hf;this.ya=null;this.ba="";this.ab=a.ef;this.Db={};this.Ua=this.wa=null;this.Pb=[];this.H=this.za=null;this.Sc=!1;this.Ed=0;this.rb=null;this.$a=-1;this.We=()=>this.Le();this.Za=[];this.v=a.Yd;this.Tb="file"===location.protocol.substr(0,4);!this.ca||"undefined"!==typeof OffscreenCanvas&&navigator.userActivation&&ja()||(this.ca=!1);this.ca&&ea&&(this.ca=!1);if("playable-ad"===this.v||"instant-games"===this.v)this.ca=!1;if("cordova"===this.v&&this.ca)if(y){const c=
/Chrome\/(\d+)/i.exec(navigator.userAgent);c&&90<=parseInt(c[1],10)||(this.ca=!1)}else this.ca=!1;this.Wb=this.ta=null;"html5"!==this.v||window.isSecureContext||console.warn("[Construct] Warning: the browser indicates this is not a secure context. Some features may be unavailable. Use secure (HTTPS) hosting to ensure all features are available.");this.C("runtime","cordova-fetch-local-file",c=>this.He(c));this.C("runtime","create-job-worker",()=>this.Ie());"cordova"===this.v?document.addEventListener("deviceready",
()=>this.ud(a)):this.ud(a)}j(){this.xc();this.ya&&(this.ya=this.ya.onmessage=null);this.wa&&(this.wa.terminate(),this.wa=null);this.Ua&&(this.Ua.j(),this.Ua=null);this.H&&(this.H.parentElement.removeChild(this.H),this.H=null)}te(){return da&&"cordova"===this.v}tc(){const a=navigator.userAgent;return da&&va.has(this.v)||navigator.standalone||/crios\/|fxios\/|edgios\//i.test(a)}re(){return y}sc(){return y&&va.has(this.v)}async ud(a){"macos-wkwebview"===this.v&&this.Hc({type:"ready"});if("playable-ad"===
this.v){this.ta=self.c3_base64files;this.Wb={};await this.Ae();for(let d=0,e=a.cb.length;d<e;++d){var c=a.cb[d];this.Wb.hasOwnProperty(c)?a.cb[d]={bf:!0,ff:this.Wb[c]}:this.ta.hasOwnProperty(c)&&(a.cb[d]=URL.createObjectURL(this.ta[c]))}a.lc=[]}if("nwjs"===this.v&&self.nw&&self.nw.App.manifest["c3-steam-mode"]){let d=0;this.rd(()=>{d++;document.body.style.opacity=0===d%2?"1":"0.999"})}a.df?this.ba=a.df:(c=location.origin,this.ba=("null"===c?"file:///":c)+location.pathname,c=this.ba.lastIndexOf("/"),
-1!==c&&(this.ba=this.ba.substr(0,c+1)));a.kf&&(this.Db=a.kf);c=new MessageChannel;this.ya=c.port1;this.ya.onmessage=d=>this._OnMessageFromRuntime(d.data);window.c3_addPortMessageHandler&&window.c3_addPortMessageHandler(d=>this.Ke(d));this.rb=new self.ue(this);await xa(this.rb);"object"===typeof window.StatusBar&&window.StatusBar.hide();if("object"===typeof window.AndroidFullScreen)try{await new Promise((d,e)=>{window.AndroidFullScreen.immersiveMode(d,e)})}catch(d){console.error("Failed to enter Android immersive mode: ",
d)}this.ca?await this.Ge(a,c.port2):await this.Fe(a,c.port2)}zc(a){a=this.Db.hasOwnProperty(a)?this.Db[a]:a.endsWith("/workermain.js")&&this.Db.hasOwnProperty("workermain.js")?this.Db["workermain.js"]:"playable-ad"===this.v&&this.ta.hasOwnProperty(a)?this.ta[a]:a;a instanceof Blob&&(a=URL.createObjectURL(a));return a}async nc(a,c,d){if(a.startsWith("blob:"))return new Worker(a,d);if("cordova"===this.v&&this.Tb)return a=await this.Eb(d.af?a:this.ab+a),new Worker(URL.createObjectURL(new Blob([a],{type:"application/javascript"})),
d);a=new URL(a,c);if(location.origin!==a.origin){a=await fetch(a);if(!a.ok)throw Error("failed to fetch worker script");a=await a.blob();return new Worker(URL.createObjectURL(a),d)}return new Worker(a,d)}ra(){return Math.max(window.innerWidth,1)}ka(){return Math.max(window.innerHeight,1)}td(a){var c=this.ba,d=location.href,e=this.ra(),f=this.ka(),g=window.devicePixelRatio,h=b.hb(),k=a.sf,q=window.cr_previewImageBlobs||this.ta,p=window.cr_previewProjectFileBlobs,C=window.cr_previewProjectFiles,z=window.qf||
"";a=a.Yd;var r=(new URLSearchParams(self.location.search)).has("debug"),D=this.rb;return{runtimeBaseUrl:c,previewUrl:d,windowInnerWidth:e,windowInnerHeight:f,devicePixelRatio:g,isFullscreen:h,projectData:k,previewImageBlobs:q,previewProjectFileBlobs:p,previewProjectFileSWUrls:C,swClientId:z,exportType:a,isDebug:r,ife:!!self.rf,jobScheduler:{inputPort:D.Rc,outputPort:D.$c,maxNumWorkers:D.Te},supportedAudioFormats:ka,opusWasmScriptUrl:window.cr_opusWasmScriptUrl||this.ab+"opus.wasm.js",opusWasmBinaryUrl:window.cr_opusWasmBinaryUrl||
this.ab+"opus.wasm.wasm",isFileProtocol:this.Tb,isiOSCordova:this.te(),isiOSWebView:this.tc(),isFBInstantAvailable:"undefined"!==typeof self.FBInstant}}async Ge(a,c){const d=this.zc(a.jf);"preview"===this.v?(this.wa=new Worker("previewworker.js",{type:"module",name:"Runtime"}),await new Promise((h,k)=>{const q=p=>{this.wa.removeEventListener("message",q);p.data&&"ok"===p.data.type?h():k()};this.wa.addEventListener("message",q);this.wa.postMessage({type:"construct-worker-init","import":(new URL(d,
this.ba)).toString()})})):this.wa=await this.nc(d,this.ba,{type:"module",name:"Runtime",af:!0});this.H=document.createElement("canvas");this.H.style.display="none";const e=this.H.transferControlToOffscreen();document.body.appendChild(this.H);window.c3canvas=this.H;self.C3_InsertHTMLPlaceholders&&self.C3_InsertHTMLPlaceholders();let f=a.lc||[],g=a.cb;f=await Promise.all(f.map(h=>this.Oa(h)));g=await Promise.all(g.map(h=>this.Oa(h)));if("cordova"===this.v)for(let h=0,k=a.kc.length;h<k;++h){const q=
a.kc[h],p=q[0];if(p===a.ed||"scriptsInEvents.js"===p||p.endsWith("/scriptsInEvents.js"))q[1]=await this.Oa(p)}this.wa.postMessage(Object.assign(this.td(a),{type:"init-runtime",isInWorker:!0,messagePort:c,canvas:e,workerDependencyScripts:f,engineScripts:g,projectScripts:a.kc,mainProjectScript:a.ed,projectScriptsStatus:self.C3_ProjectScriptsStatus}),[c,e,...ya(this.rb)]);this.Pb=F.map(h=>new h(this));this.sd();za(this.za);self.c3_callFunction=(h,k)=>{var q=this.za;return q.o.pd(q.mb,"js-invoke-function",
{name:h,params:k},void 0,void 0)};"preview"===this.v&&(self.goToLastErrorScript=()=>this.Gb("runtime","go-to-last-error-script"))}async Fe(a,c){this.H=document.createElement("canvas");this.H.style.display="none";document.body.appendChild(this.H);window.c3canvas=this.H;self.C3_InsertHTMLPlaceholders&&self.C3_InsertHTMLPlaceholders();this.Pb=F.map(g=>new g(this));this.sd();var d=a.cb.map(g=>"string"===typeof g?(new URL(g,this.ba)).toString():g);Array.isArray(a.lc)&&d.unshift(...a.lc);d=await Promise.all(d.map(g=>
this.Oa(g)));await Promise.all(d.map(g=>A(g)));d=self.C3_ProjectScriptsStatus;const e=a.ed,f=a.kc;for(let [g,h]of f)if(h||(h=g),g===e)try{h=await this.Oa(h),await A(h),"preview"!==this.v||d[g]||this.wd(g,"main script did not run to completion")}catch(k){this.wd(g,k)}else if("scriptsInEvents.js"===g||g.endsWith("/scriptsInEvents.js"))h=await this.Oa(h),await A(h);"preview"===this.v&&"object"!==typeof self.lf.nf?(this.Kb(),console.error("[C3 runtime] Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax."),
alert("Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax.")):(a=Object.assign(this.td(a),{isInWorker:!1,messagePort:c,canvas:this.H,runOnStartupFunctions:ua}),za(this.za),this.vd(),this.Ua=self.C3_CreateRuntime(a),await self.C3_InitRuntime(this.Ua,a))}wd(a,c){this.Kb();console.error(`[Preview] Failed to load project main script (${a}): `,c);alert(`Failed to load project main script (${a}). Check all your JavaScript code has valid syntax. Press F12 and check the console for error details.`)}vd(){this.Kb()}Kb(){const a=
window.Ze;a&&(a.parentElement.removeChild(a),window.Ze=null)}async Ie(){const a=await Aa(this.rb);return{outputPort:a,transferables:[a]}}Ee(){if(this.ca)throw Error("not available in worker mode");return this.Ua}Gb(a,c,d,e,f){this.ya.postMessage({type:"event",component:a,handler:c,dispatchOpts:e||null,data:d,responseId:null},f)}pd(a,c,d,e,f){const g=ta++,h=new Promise((k,q)=>{sa.set(g,{resolve:k,reject:q})});this.ya.postMessage({type:"event",component:a,handler:c,dispatchOpts:e||null,data:d,responseId:g},
f);return h}_OnMessageFromRuntime(a){const c=a.type;if("event"===c)return this.Je(a);if("result"===c)this.Me(a);else if("runtime-ready"===c)this.Ne();else if("alert-error"===c)this.Kb(),alert(a.message);else if("creating-runtime"===c)this.vd();else throw Error(`unknown message '${c}'`);}Je(a){const c=a.component,d=a.handler,e=a.data,f=a.responseId;if(a=ra.get(c))if(a=a.get(d)){var g=null;try{g=a(e)}catch(h){console.error(`Exception in '${c}' handler '${d}':`,h);null!==f&&this.Jb(f,!1,""+h);return}if(null===
f)return g;g&&g.then?g.then(h=>this.Jb(f,!0,h)).catch(h=>{console.error(`Rejection from '${c}' handler '${d}':`,h);this.Jb(f,!1,""+h)}):this.Jb(f,!0,g)}else console.warn(`[DOM] No handler '${d}' for component '${c}'`);else console.warn(`[DOM] No event handlers for component '${c}'`)}Jb(a,c,d){let e;d&&d.transferables&&(e=d.transferables);this.ya.postMessage({type:"result",responseId:a,isOk:c,result:d},e)}Me(a){const c=a.responseId,d=a.isOk;a=a.result;const e=sa.get(c);d?e.resolve(a):e.reject(a);sa.delete(c)}C(a,
c,d){let e=ra.get(a);e||(e=new Map,ra.set(a,e));if(e.has(c))throw Error(`[DOM] Component '${a}' already has handler '${c}'`);e.set(c,d)}static La(a){if(F.includes(a))throw Error("DOM handler already added");F.push(a)}sd(){for(const a of this.Pb)if("runtime"===a.mb){this.za=a;return}throw Error("cannot find runtime DOM handler");}Ke(a){this.Gb("debugger","message",a)}Ne(){for(const a of this.Pb)a.gd()}static hb(){return!!(document.fullscreenElement||document.webkitFullscreenElement||document.mozFullScreenElement||
wa)}static Lb(a){wa=!!a}rd(a){this.Za.push(a);this.Gc()}Pe(a){a=this.Za.indexOf(a);if(-1===a)throw Error("invalid callback");this.Za.splice(a,1);this.Za.length||this.xc()}Gc(){-1===this.$a&&this.Za.length&&(this.$a=requestAnimationFrame(this.We))}xc(){-1!==this.$a&&(cancelAnimationFrame(this.$a),this.$a=-1)}Le(){this.$a=-1;for(const a of this.Za)a();this.Gc()}ea(a){this.za.ea(a)}ja(a){this.za.ja(a)}Fc(){this.za.Fc()}Ib(a){this.za.Ib(a)}se(){return!!ka["audio/webm; codecs=opus"]}async Qe(a){a=await this.pd("runtime",
"opus-decode",{arrayBuffer:a},null,[a]);return new Float32Array(a)}we(a){this.Sc=!0;this.Ed=a}qe(a){return/^(?:[a-z\-]+:)?\/\//.test(a)||"data:"===a.substr(0,5)||"blob:"===a.substr(0,5)}od(a){return!this.qe(a)}async Oa(a){return"cordova"===this.v&&(a.startsWith("file:")||this.Tb&&this.od(a))?(a.startsWith(this.ba)&&(a=a.substr(this.ba.length)),a=await this.Eb(a),URL.createObjectURL(new Blob([a],{type:"application/javascript"}))):a}async He(a){const c=a.filename;switch(a.as){case "text":return await this.oe(c);
case "buffer":return await this.Eb(c);default:throw Error("unsupported type");}}kd(a){const c=window.cordova.file.applicationDirectory+"www/"+a;return new Promise((d,e)=>{window.resolveLocalFileSystemURL(c,f=>{f.file(d,e)},e)})}async oe(a){a=await this.kd(a);return await la(a)}yc(){if(na.length&&!(8<=E)){E++;var a=na.shift();this.Be(a.filename,a.gf,a.$e)}}Eb(a){return new Promise((c,d)=>{na.push({filename:a,gf:e=>{E--;this.yc();c(e)},$e:e=>{E--;this.yc();d(e)}});this.yc()})}async Be(a,c,d){try{const e=
await this.kd(a),f=await ma(e);c(f)}catch(e){d(e)}}Hc(a){if("windows-webview2"===this.v)window.chrome.webview.postMessage(JSON.stringify(a));else if("macos-wkwebview"===this.v)window.webkit.messageHandlers.C3Wrapper.postMessage(JSON.stringify(a));else throw Error("cannot send wrapper message");}async Ae(){const a=[];for(const [c,d]of Object.entries(this.ta))a.push(this.ze(c,d));await Promise.all(a)}async ze(a,c){if("object"===typeof c)this.ta[a]=new Blob([c.str],{type:c.type}),this.Wb[a]=c.str;else{let d=
await this.De(c);d||(d=this.Ce(c));this.ta[a]=d}}async De(a){try{return await (await fetch(a)).blob()}catch(c){return console.warn("Failed to fetch a data: URI. Falling back to a slower workaround. This is probably because the Content Security Policy unnecessarily blocked it. Allow data: URIs in your CSP to avoid this.",c),null}}Ce(a){a=this.Oe(a);return this.ye(a.data,a.cf)}Oe(a){var c=a.indexOf(",");if(0>c)throw new URIError("expected comma in data: uri");var d=a.substring(c+1);c=a.substring(5,
c).split(";");a=c[0]||"";const e=c[2];d="base64"===c[1]||"base64"===e?atob(d):decodeURIComponent(d);return{cf:a,data:d}}ye(a,c){var d=a.length;let e=d>>2,f=new Uint8Array(d),g=new Uint32Array(f.buffer,0,e),h,k;for(k=h=0;h<e;++h)g[h]=a.charCodeAt(k++)|a.charCodeAt(k++)<<8|a.charCodeAt(k++)<<16|a.charCodeAt(k++)<<24;for(d&=3;d--;)f[k]=a.charCodeAt(k),++k;return new Blob([f],{type:c})}};"use strict";const H=self.qa;
function Ba(b){return b.sourceCapabilities&&b.sourceCapabilities.firesTouchEvents||b.originalEvent&&b.originalEvent.sourceCapabilities&&b.originalEvent.sourceCapabilities.firesTouchEvents}const Ca=new Map([["OSLeft","MetaLeft"],["OSRight","MetaRight"]]),I={dispatchRuntimeEvent:!0,dispatchUserScriptEvent:!0},Da={dispatchUserScriptEvent:!0},Ea={dispatchRuntimeEvent:!0};
function Fa(b){return new Promise((a,c)=>{const d=document.createElement("link");d.onload=()=>a(d);d.onerror=e=>c(e);d.rel="stylesheet";d.href=b;document.head.appendChild(d)})}function Ga(b){return new Promise((a,c)=>{const d=new Image;d.onload=()=>a(d);d.onerror=e=>c(e);d.src=b})}async function J(b){b=URL.createObjectURL(b);try{return await Ga(b)}finally{URL.revokeObjectURL(b)}}
function Ha(b){return new Promise((a,c)=>{let d=new FileReader;d.onload=e=>a(e.target.result);d.onerror=e=>c(e);d.readAsText(b)})}
async function Ia(b,a,c){if(!/firefox/i.test(navigator.userAgent))return await J(b);var d=await Ha(b);d=(new DOMParser).parseFromString(d,"image/svg+xml");const e=d.documentElement;if(e.hasAttribute("width")&&e.hasAttribute("height")){const f=e.getAttribute("width"),g=e.getAttribute("height");if(!f.includes("%")&&!g.includes("%"))return await J(b)}e.setAttribute("width",a+"px");e.setAttribute("height",c+"px");d=(new XMLSerializer).serializeToString(d);b=new Blob([d],{type:"image/svg+xml"});return await J(b)}
function Ja(b){do{if(b.parentNode&&b.hasAttribute("contenteditable"))return!0;b=b.parentNode}while(b);return!1}const Ka=new Set(["input","textarea","datalist","select"]),La=new Set(["canvas","body","html"]);function K(b){b.target.tagName&&La.has(b.target.tagName.toLowerCase())&&b.preventDefault()}function Na(b){(b.metaKey||b.ctrlKey)&&b.preventDefault()}
self.C3_GetSvgImageSize=async function(b){b=await J(b);if(0<b.width&&0<b.height)return[b.width,b.height];b.style.position="absolute";b.style.left="0px";b.style.top="0px";b.style.visibility="hidden";document.body.appendChild(b);const a=b.getBoundingClientRect();document.body.removeChild(b);return[a.width,a.height]};self.C3_RasterSvgImageBlob=async function(b,a,c,d,e){b=await Ia(b,a,c);const f=document.createElement("canvas");f.width=d;f.height=e;f.getContext("2d").drawImage(b,0,0,a,c);return f};
let Oa=!1;document.addEventListener("pause",()=>Oa=!0);document.addEventListener("resume",()=>Oa=!1);function za(b){b.Dd=!0;b.Xc=b.o.ra();b.sb=b.o.ka()}async function Pa(b){await Promise.all(b.webfonts.map(async a=>{a=new FontFace(a.name,`url('${a.url}')`);document.fonts.add(a);await a.load()}))}
async function Qa(b){var a=b.imageBitmapOpts;b=await self.C3_RasterSvgImageBlob(b.blob,b.imageWidth,b.imageHeight,b.surfaceWidth,b.surfaceHeight);a=a?await createImageBitmap(b,a):await createImageBitmap(b);return{imageBitmap:a,transferables:[a]}}async function Ra(b){return await self.C3_GetSvgImageSize(b.blob)}function Sa(b){window.c3_postToMessagePort&&(b.from="runtime",window.c3_postToMessagePort(b))}
function Ta(b){self.setTimeout(()=>{b.Cd=!0},1E3);"cordova"===b.o.v?(document.addEventListener("pause",()=>Ua(b,!0)),document.addEventListener("resume",()=>Ua(b,!1))):document.addEventListener("visibilitychange",()=>Ua(b,document.hidden));return{isSuspended:!(!document.hidden&&!Oa)}}
function Va(b){b.yd||(b.yd=!0,window.addEventListener("deviceorientation",a=>{b.Z||l(b,"deviceorientation",{absolute:!!a.absolute,alpha:a.alpha||0,beta:a.beta||0,gamma:a.gamma||0,timeStamp:a.timeStamp,webkitCompassHeading:a.webkitCompassHeading,webkitCompassAccuracy:a.webkitCompassAccuracy},I)}),window.addEventListener("deviceorientationabsolute",a=>{b.Z||l(b,"deviceorientationabsolute",{absolute:!!a.absolute,alpha:a.alpha||0,beta:a.beta||0,gamma:a.gamma||0,timeStamp:a.timeStamp},I)}))}
function Wa(b){b.xd||(b.xd=!0,window.addEventListener("devicemotion",a=>{if(!b.Z){var c=null,d=a.acceleration;d&&(c={x:d.x||0,y:d.y||0,z:d.z||0});d=null;var e=a.accelerationIncludingGravity;e&&(d={x:e.x||0,y:e.y||0,z:e.z||0});e=null;var f=a.rotationRate;f&&(e={alpha:f.alpha||0,beta:f.beta||0,gamma:f.gamma||0});l(b,"devicemotion",{acceleration:c,accelerationIncludingGravity:d,rotationRate:e,interval:a.interval,timeStamp:a.timeStamp},I)}}))}async function Xa(b){await Fa(b.url)}
function Ya(b,a){b.Fd=a.message;-1===b.Mc&&(b.Mc=setTimeout(()=>{b.Mc=-1;const c=document.getElementById("exportToVideoMessage");c&&(c.textContent=b.Fd)},250))}function L(b){if(!b.Z){var a=H.hb();a&&"any"!==b.bd&&Za(b);l(b,"fullscreenchange",{isFullscreen:a,innerWidth:b.ra(),innerHeight:b.ka()})}}function $a(b,a){console.warn("[Construct] Fullscreen request failed: ",a);l(b,"fullscreenerror",{isFullscreen:H.hb(),innerWidth:b.ra(),innerHeight:b.ka()})}
function Ua(b,a){a?b.o.xc():b.o.Gc();l(b,"visibilitychange",{hidden:a})}function ab(b,a,c){"Backspace"===c.key&&K(c);if(!b.Z){var d=Ca.get(c.code)||c.code;m(b,a,{code:d,key:c.key,which:c.which,repeat:c.repeat,altKey:c.altKey,ctrlKey:c.ctrlKey,metaKey:c.metaKey,shiftKey:c.shiftKey,timeStamp:c.timeStamp},I)}}
function bb(b,a,c,d){b.Z||Ba(c)||m(b,a,{button:c.button,buttons:c.buttons,clientX:c.clientX,clientY:c.clientY+b.da,pageX:c.pageX,pageY:c.pageY+b.da,movementX:c.movementX||0,movementY:c.movementY||0,timeStamp:c.timeStamp},d)}function cb(b){window!==window.top&&window.focus();db(b.target)&&document.activeElement&&!db(document.activeElement)&&document.activeElement.blur()}
function M(b,a,c){if(!b.Z){var d=0;"mouse"===c.pointerType&&(d=b.xb);m(b,a,{pointerId:c.pointerId,pointerType:c.pointerType,button:c.button,buttons:c.buttons,lastButtons:d,clientX:c.clientX,clientY:c.clientY+b.da,pageX:c.pageX,pageY:c.pageY+b.da,movementX:c.movementX||0,movementY:c.movementY||0,width:c.width||0,height:c.height||0,pressure:c.pressure||0,tangentialPressure:c.tangentialPressure||0,tiltX:c.tiltX||0,tiltY:c.tiltY||0,twist:c.twist||0,timeStamp:c.timeStamp},I);"mouse"===c.pointerType&&(d=
"mousemove","pointerdown"===a?d="mousedown":"pointerup"===a&&(d="mouseup"),bb(b,d,c,Da),b.xb=c.buttons)}}
function fb(b,a,c){if(!b.Z&&!Ba(c)){var d=b.xb;"pointerdown"===a&&0!==d?a="pointermove":"pointerup"===a&&0!==c.buttons&&(a="pointermove");m(b,a,{pointerId:1,pointerType:"mouse",button:c.button,buttons:c.buttons,lastButtons:d,clientX:c.clientX,clientY:c.clientY+b.da,pageX:c.pageX,pageY:c.pageY+b.da,movementX:c.movementX||0,movementY:c.movementY||0,width:0,height:0,pressure:0,tangentialPressure:0,tiltX:0,tiltY:0,twist:0,timeStamp:c.timeStamp},I);b.xb=c.buttons;bb(b,c.type,c,Da)}}
function N(b,a,c){if(!b.Z)for(let d=0,e=c.changedTouches.length;d<e;++d){const f=c.changedTouches[d];m(b,a,{pointerId:f.identifier,pointerType:"touch",button:0,buttons:0,lastButtons:0,clientX:f.clientX,clientY:f.clientY+b.da,pageX:f.pageX,pageY:f.pageY+b.da,movementX:c.movementX||0,movementY:c.movementY||0,width:2*(f.radiusX||f.webkitRadiusX||0),height:2*(f.radiusY||f.webkitRadiusY||0),pressure:f.force||f.webkitForce||0,tangentialPressure:0,tiltX:0,tiltY:0,twist:f.rotationAngle||0,timeStamp:c.timeStamp},
I)}}function gb(b,a,c){document.body.style.transform="";b.da=0;if(0<c){var d=document.activeElement;d&&(d=d.getBoundingClientRect(),a=(d.top+d.bottom)/2-(a-c)/2,a>c&&(a=c),0>a&&(a=0),0<a&&(document.body.style.transform=`translateY(${-a}px)`,b.da=a))}}function hb(b,a,c,d){const e=b.ra(),f=b.ka();b.bb=-1;e!=a||f!=c?l(b,"window-resize",{innerWidth:e,innerHeight:f,devicePixelRatio:window.devicePixelRatio,isFullscreen:H.hb()}):10>d&&ib(b,e,f,d+1)}
function ib(b,a,c,d){-1!==b.bb&&clearTimeout(b.bb);b.bb=setTimeout(()=>hb(b,a,c,d),48)}
function Za(b){b=b.bd;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(b).catch(a=>console.warn("[Construct] Failed to lock orientation: ",a));else try{let a=!1;screen.lockOrientation?a=screen.lockOrientation(b):screen.webkitLockOrientation?a=screen.webkitLockOrientation(b):screen.mozLockOrientation?a=screen.mozLockOrientation(b):screen.msLockOrientation&&(a=screen.msLockOrientation(b));a||console.warn("[Construct] Failed to lock orientation")}catch(a){console.warn("[Construct] Failed to lock orientation: ",
a)}}function db(b){return!b||b===document||b===window||b===document.body||"canvas"===b.tagName.toLowerCase()}
H.La(class extends self.Ma{constructor(b){super(b,"runtime");this.Kd=!0;this.Dd=!1;this.bb=-1;this.bd="any";this.xd=this.yd=!1;this.fc=document.createElement("div");this.fc.className="c3-screen-reader-text";this.fc.setAttribute("aria-live","polite");document.body.appendChild(this.fc);this.Ha=null;this.Z=!1;this.Fd="";this.Mc=-1;this.Cd=!1;this.Xc=b.ra();this.sb=b.ka();this.da=this.Cb=0;b.C("canvas","update-size",d=>{var e=this.o;e.Sc||(e=e.H,e.style.width=d.styleWidth+"px",e.style.height=d.styleHeight+
"px",e.style.marginLeft=d.marginLeft+"px",e.style.marginTop=d.marginTop+"px",document.documentElement.style.setProperty("--construct-scale",d.displayScale),this.Kd&&(e.style.display="",this.Kd=!1))});b.C("runtime","invoke-download",d=>{const e=d.url;d=d.filename;const f=document.createElement("a"),g=document.body;f.textContent=d;f.href=e;f.download=d;g.appendChild(f);f.click();g.removeChild(f)});b.C("runtime","load-webfonts",d=>Pa(d));b.C("runtime","raster-svg-image",d=>Qa(d));b.C("runtime","get-svg-image-size",
d=>Ra(d));b.C("runtime","set-target-orientation",d=>{this.bd=d.targetOrientation});b.C("runtime","register-sw",()=>{window.C3_RegisterSW&&window.C3_RegisterSW()});b.C("runtime","post-to-debugger",d=>Sa(d));b.C("runtime","go-to-script",d=>Sa(d));b.C("runtime","before-start-ticking",()=>Ta(this));b.C("runtime","debug-highlight",d=>{if(d.show){this.Ha||(this.Ha=document.createElement("div"),this.Ha.id="inspectOutline",document.body.appendChild(this.Ha));var e=this.Ha;e.style.display="";e.style.left=
d.left-1+"px";e.style.top=d.top-1+"px";e.style.width=d.width+2+"px";e.style.height=d.height+2+"px";e.textContent=d.name}else this.Ha&&(this.Ha.style.display="none")});b.C("runtime","enable-device-orientation",()=>Va(this));b.C("runtime","enable-device-motion",()=>Wa(this));b.C("runtime","add-stylesheet",d=>Xa(d));b.C("runtime","script-create-worker",d=>{const e=d.port2;(new Worker(d.url,d.opts)).postMessage({type:"construct-worker-init",port2:e},[e])});b.C("runtime","alert",d=>this.Cc(d));b.C("runtime",
"screen-reader-text",d=>{var e=d.type;"create"===e?(e=document.createElement("p"),e.id="c3-sr-"+d.id,e.textContent=d.text,this.fc.appendChild(e)):"update"===e?(e=document.getElementById("c3-sr-"+d.id))?e.textContent=d.text:console.warn(`[Construct] Missing screen reader text with id ${d.id}`):"release"===e?(e=document.getElementById("c3-sr-"+d.id))?e.remove():console.warn(`[Construct] Missing screen reader text with id ${d.id}`):console.warn(`[Construct] Unknown screen reader text update '${e}'`)});
b.C("runtime","hide-cordova-splash",()=>{navigator.splashscreen&&navigator.splashscreen.hide&&navigator.splashscreen.hide()});b.C("runtime","set-exporting-to-video",d=>{this.Z=!0;const e=document.createElement("h1");e.id="exportToVideoMessage";e.textContent=d.message;document.body.prepend(e);document.body.classList.add("exportingToVideo");this.o.H.style.display="";this.o.we(d.duration)});b.C("runtime","export-to-video-progress",d=>Ya(this,d));b.C("runtime","exported-to-video",d=>{window.Ye({type:"exported-video",
blob:d.blob,time:d.time})});b.C("runtime","exported-to-image-sequence",d=>{window.Ye({type:"exported-image-sequence",blobArr:d.blobArr,time:d.time,gif:d.gif})});const a=new Set(["input","textarea","datalist"]);window.addEventListener("contextmenu",d=>{const e=d.target;a.has(e.tagName.toLowerCase())||Ja(e)||d.preventDefault()});const c=b.H;window.addEventListener("selectstart",K);window.addEventListener("gesturehold",K);c.addEventListener("selectstart",K);c.addEventListener("gesturehold",K);window.addEventListener("touchstart",
K,{passive:!1});"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",K,{passive:!1}),c.addEventListener("pointerdown",K)):c.addEventListener("touchstart",K);this.xb=0;window.addEventListener("mousedown",d=>{1===d.button&&d.preventDefault()});window.addEventListener("mousewheel",Na,{passive:!1});window.addEventListener("wheel",Na,{passive:!1});window.addEventListener("resize",()=>{a:{if(!this.Z&&this.Dd){var d=this.ra();var e=this.ka();if(this.o.sc()){if(this.Cd){if(this.Xc===d&&
e<this.sb){this.Cb=this.sb-e;gb(this,this.sb,this.Cb);d=void 0;break a}0<this.Cb&&(this.Cb=0,gb(this,e,this.Cb))}this.Xc=d;this.sb=e}l(this,"window-resize",{innerWidth:d,innerHeight:e,devicePixelRatio:window.devicePixelRatio,isFullscreen:H.hb()});this.o.tc()&&(-1!==this.bb&&clearTimeout(this.bb),hb(this,d,e,0))}d=void 0}return d});window.addEventListener("fullscreenchange",()=>L(this));window.addEventListener("webkitfullscreenchange",()=>L(this));window.addEventListener("mozfullscreenchange",()=>
L(this));window.addEventListener("fullscreenerror",d=>$a(this,d));window.addEventListener("webkitfullscreenerror",d=>$a(this,d));window.addEventListener("mozfullscreenerror",d=>$a(this,d));if(b.tc())if(window.visualViewport){let d=Infinity;window.visualViewport.addEventListener("resize",()=>{const e=window.visualViewport.height;e>d&&(document.scrollingElement.scrollTop=0);d=e})}else window.addEventListener("focusout",()=>{{const f=document.activeElement;if(f){var d=f.tagName.toLowerCase();var e=new Set("email number password search tel text url".split(" "));
d="textarea"===d?!0:"input"===d?e.has(f.type.toLowerCase()||"text"):Ja(f)}else d=!1}d||(document.scrollingElement.scrollTop=0)});self.C3WrapperOnMessage=d=>{"entered-fullscreen"===d?(H.Lb(!0),L(this)):"exited-fullscreen"===d?(H.Lb(!1),L(this)):console.warn("Unknown wrapper message: ",d)};this.Va=new Set;this.Yb=new WeakSet;this.xa=!1}gd(){window.addEventListener("focus",()=>{l(this,"window-focus",null,Ea)});window.addEventListener("blur",()=>{try{var a=window.parent&&window.parent.document.hasFocus()}catch(c){a=
!1}l(this,"window-blur",{parentHasFocus:a},Ea);this.xb=0});window.addEventListener("focusin",a=>{a=a.target;(Ka.has(a.tagName.toLowerCase())||Ja(a))&&l(this,"keyboard-blur",null,Ea)});window.addEventListener("keydown",a=>ab(this,"keydown",a));window.addEventListener("keyup",a=>ab(this,"keyup",a));window.addEventListener("dblclick",a=>bb(this,"dblclick",a,I));window.addEventListener("wheel",a=>{this.Z||l(this,"wheel",{clientX:a.clientX,clientY:a.clientY+this.da,pageX:a.pageX,pageY:a.pageY+this.da,
deltaX:a.deltaX,deltaY:a.deltaY,deltaZ:a.deltaZ,deltaMode:a.deltaMode,timeStamp:a.timeStamp},I)});"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",a=>{cb(a);M(this,"pointerdown",a)}),this.o.ca&&"undefined"!==typeof window.onpointerrawupdate&&self===self.top?window.addEventListener("pointerrawupdate",a=>{M(this,"pointermove",a)}):window.addEventListener("pointermove",a=>M(this,"pointermove",a)),window.addEventListener("pointerup",a=>M(this,"pointerup",a)),window.addEventListener("pointercancel",
a=>M(this,"pointercancel",a))):(window.addEventListener("mousedown",a=>{cb(a);fb(this,"pointerdown",a)}),window.addEventListener("mousemove",a=>fb(this,"pointermove",a)),window.addEventListener("mouseup",a=>fb(this,"pointerup",a)),window.addEventListener("touchstart",a=>{cb(a);N(this,"pointerdown",a)}),window.addEventListener("touchmove",a=>N(this,"pointermove",a)),window.addEventListener("touchend",a=>N(this,"pointerup",a)),window.addEventListener("touchcancel",a=>N(this,"pointercancel",a)));const b=
()=>this.Fc();window.addEventListener("pointerup",b,!0);window.addEventListener("touchend",b,!0);window.addEventListener("click",b,!0);window.addEventListener("keydown",b,!0);window.addEventListener("gamepadconnected",b,!0);this.o.re()&&!this.o.sc()&&navigator.virtualKeyboard&&(navigator.virtualKeyboard.overlaysContent=!0,navigator.virtualKeyboard.addEventListener("geometrychange",()=>{gb(this,this.ka(),navigator.virtualKeyboard.boundingRect.height)}))}ra(){return this.o.ra()}ka(){return this.o.ka()}Fc(){var b=
[...this.Va];this.Va.clear();if(!this.xa)for(const a of b)(b=a.play())&&b.catch(()=>{this.Yb.has(a)||this.Va.add(a)})}ea(b){if("function"!==typeof b.play)throw Error("missing play function");this.Yb.delete(b);let a;try{a=b.play()}catch(c){this.Va.add(b);return}a&&a.catch(()=>{this.Yb.has(b)||this.Va.add(b)})}ja(b){this.Va.delete(b);this.Yb.add(b)}Ib(b){this.xa=!!b}Cc(b){alert(b.message)}});"use strict";
async function xa(b){if(b.Re)throw Error("already initialised");b.Re=!0;var a=b.Aa.zc(("playable-ad"===b.Aa.v?b.Aa.ab:"")+"dispatchworker.js");b.Lc=await b.Aa.nc(a,b.lb,{name:"DispatchWorker"});a=new MessageChannel;b.Rc=a.port1;b.Lc.postMessage({type:"_init","in-port":a.port2},[a.port2]);b.$c=await Aa(b)}function ya(b){return[b.Rc,b.$c]}
async function Aa(b){const a=b.Ld.length;var c=b.Aa.zc(("playable-ad"===b.Aa.v?b.Aa.ab:"")+"jobworker.js");c=await b.Aa.nc(c,b.lb,{name:"JobWorker"+a});const d=new MessageChannel,e=new MessageChannel;b.Lc.postMessage({type:"_addJobWorker",port:d.port1},[d.port1]);c.postMessage({type:"init",number:a,"dispatch-port":d.port2,"output-port":e.port2},[d.port2,e.port2]);b.Ld.push(c);return e.port1}
self.ue=class{constructor(b){this.Aa=b;this.lb=b.ba;this.lb="preview"===b.v?this.lb+"workers/":this.lb+b.ab;this.Te=Math.min(navigator.hardwareConcurrency||2,16);this.Lc=null;this.Ld=[];this.$c=this.Rc=null}};"use strict";window.C3_IsSupported&&(window.c3_runtimeInterface=new self.qa({hf:!0,jf:"workermain.js",cb:["scripts/c3runtime.js"],kc:[],ed:"",ef:"scripts/",lc:["box2d.wasm.js"],Yd:"html5"}));"use strict";
async function jb(b,a){a=a.type;let c=!0;0===a?c=await kb():1===a&&(c=await lb());l(b,"permission-result",{type:a,result:c})}async function kb(){if(!self.DeviceOrientationEvent||!self.DeviceOrientationEvent.requestPermission)return!0;try{return"granted"===await self.DeviceOrientationEvent.requestPermission()}catch(b){return console.warn("[Touch] Failed to request orientation permission: ",b),!1}}
async function lb(){if(!self.DeviceMotionEvent||!self.DeviceMotionEvent.requestPermission)return!0;try{return"granted"===await self.DeviceMotionEvent.requestPermission()}catch(b){return console.warn("[Touch] Failed to request motion permission: ",b),!1}}self.qa.La(class extends self.Ma{constructor(b){super(b,"touch");n(this,"request-permission",a=>jb(this,a))}});"use strict";
self.qa.La(class extends self.Ma{constructor(b){super(b,"mouse");t(this,[["cursor",a=>{document.documentElement.style.cursor=a}],["request-pointer-lock",()=>{this.o.H.requestPointerLock()}],["release-pointer-lock",()=>{document.exitPointerLock()}]]);document.addEventListener("pointerlockchange",()=>{l(this,"pointer-lock-change",{"has-pointer-lock":!!document.pointerLockElement})});document.addEventListener("pointerlockerror",()=>{l(this,"pointer-lock-error",{"has-pointer-lock":!!document.pointerLockElement})})}});
"use strict";function mb(){}function nb(b){window.C3_RegisterSW&&window.OfflineClientInfo&&window.OfflineClientInfo.SetMessageCallback(a=>l(b,"sw-message",a.data))}
function ob(b){b=b.orientation;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(b).catch(a=>console.warn("[Construct] Failed to lock orientation: ",a));else try{let a=!1;screen.lockOrientation?a=screen.lockOrientation(b):screen.webkitLockOrientation?a=screen.webkitLockOrientation(b):screen.mozLockOrientation?a=screen.mozLockOrientation(b):screen.msLockOrientation&&(a=screen.msLockOrientation(b));a||console.warn("[Construct] Failed to lock orientation")}catch(a){console.warn("[Construct] Failed to lock orientation: ",
a)}}
self.qa.La(class extends self.Ma{constructor(b){super(b,"browser");this.v="";t(this,[["get-initial-state",a=>{this.v=a.exportType;return{location:location.toString(),isOnline:!!navigator.onLine,referrer:document.referrer,title:document.title,isCookieEnabled:!!navigator.cookieEnabled,screenWidth:screen.width,screenHeight:screen.height,windowOuterWidth:window.outerWidth,windowOuterHeight:window.outerHeight,isConstructArcade:"undefined"!==typeof window.is_scirra_arcade}}],["ready-for-sw-messages",()=>
nb(this)],["alert",a=>this.Cc(a)],["close",()=>{navigator.app&&navigator.app.exitApp?navigator.app.exitApp():navigator.device&&navigator.device.exitApp?navigator.device.exitApp():window.close()}],["set-focus",a=>this.Ec(a)],["vibrate",a=>{navigator.vibrate&&navigator.vibrate(a.pattern)}],["lock-orientation",a=>ob(a)],["unlock-orientation",()=>{try{screen.orientation&&screen.orientation.unlock?screen.orientation.unlock():screen.unlockOrientation?screen.unlockOrientation():screen.webkitUnlockOrientation?
screen.webkitUnlockOrientation():screen.mozUnlockOrientation?screen.mozUnlockOrientation():screen.msUnlockOrientation&&screen.msUnlockOrientation()}catch(a){}}],["navigate",a=>{var c=a.type;if("back"===c)navigator.app&&navigator.app.backHistory?navigator.app.backHistory():window.history.back();else if("forward"===c)window.history.forward();else if("reload"===c)location.reload();else if("url"===c){c=a.url;const d=a.target;a=a.exportType;self.cordova&&self.cordova.InAppBrowser?self.cordova.InAppBrowser.open(c,
"_system"):"preview"===a||"windows-webview2"===a?window.open(c,"_blank"):this.pf||(2===d?window.top.location=c:1===d?window.parent.location=c:window.location=c)}else"new-window"===c&&(c=a.url,a=a.tag,self.cordova&&self.cordova.InAppBrowser?self.cordova.InAppBrowser.open(c,"_system"):window.open(c,a))}],["request-fullscreen",a=>{if("windows-webview2"===this.v||"macos-wkwebview"===this.v)self.qa.Lb(!0),this.o.Hc({type:"set-fullscreen",fullscreen:!0});else{const c={navigationUI:"auto"};a=a.navUI;1===
a?c.navigationUI="hide":2===a&&(c.navigationUI="show");a=document.documentElement;let d;a.requestFullscreen?d=a.requestFullscreen(c):a.mozRequestFullScreen?d=a.mozRequestFullScreen(c):a.msRequestFullscreen?d=a.msRequestFullscreen(c):a.webkitRequestFullScreen&&(d="undefined"!==typeof Element.ALLOW_KEYBOARD_INPUT?a.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT):a.webkitRequestFullScreen());d instanceof Promise&&d.catch(mb)}}],["exit-fullscreen",()=>{if("windows-webview2"===this.v||"macos-wkwebview"===
this.v)self.qa.Lb(!1),this.o.Hc({type:"set-fullscreen",fullscreen:!1});else{let a;document.exitFullscreen?a=document.exitFullscreen():document.mozCancelFullScreen?a=document.mozCancelFullScreen():document.msExitFullscreen?a=document.msExitFullscreen():document.webkitCancelFullScreen&&(a=document.webkitCancelFullScreen());a instanceof Promise&&a.catch(mb)}}],["set-hash",a=>{location.hash=a.hash}],["set-document-css-style",a=>{const c=a.prop,d=a.value;var e=a.selector;a=a["is-all"];try{if(e)if(a)var f=
Array.from(document.querySelectorAll(e));else{var g=document.querySelector(e);f=g?[g]:[]}else f=[document.documentElement];e=f;for(const h of e)c.startsWith("--")?h.style.setProperty(c,d):h.style[c]=d}catch(h){console.warn("[Browser] Failed to set style: ",h)}}],["get-document-css-style",a=>{{const d=a.prop;a=a.selector;try{const e=document.querySelector(a);var c=e?{isOk:!0,result:window.getComputedStyle(e).getPropertyValue(d)}:{isOk:!1}}catch(e){console.warn("[Browser] Failed to get style: ",e),
c={isOk:!1}}}return c}]]);window.addEventListener("online",()=>{l(this,"online-state",{isOnline:!0})});window.addEventListener("offline",()=>{l(this,"online-state",{isOnline:!1})});window.addEventListener("hashchange",()=>{l(this,"hashchange",{location:location.toString()})});document.addEventListener("backbutton",()=>{l(this,"backbutton")})}Cc(b){alert(b.message)}Ec(b){b=b.isFocus;if("nwjs"===this.v){const a="nwjs"===this.v?nw.Window.get():null;b?a.focus():a.blur()}else b?window.focus():window.blur()}});
"use strict";const pb=180/Math.PI;
async function qb(b,a){if(a.isiOSCordova||a.isSafari)b.bc=!0;b.cd=a.timeScaleMode;b.Qd=["equalpower","HRTF","soundfield"][a.panningModel];b.Bd=["linear","inverse","exponential"][a.distanceModel];b.Rd=a.refDistance;b.Pd=a.maxDistance;b.Td=a.rolloffFactor;if(b.o.Sc)b.bc=!0,b.g=new OfflineAudioContext({numberOfChannels:2,sampleRate:48E3,length:Math.ceil(48E3*b.o.Ed)});else{var c={latencyHint:a.latencyHint};b.Wd||(c.sampleRate=48E3);if("undefined"!==typeof AudioContext)b.g=new AudioContext(c);else if("undefined"!==
typeof webkitAudioContext)b.g=new webkitAudioContext(c);else throw Error("Web Audio API not supported");rb(b);b.g.onstatechange=()=>{"running"!==b.g.state&&rb(b);l(b,"audiocontext-state",{audioContextState:b.g.state})}}b.Qa=b.g.createGain();b.Qa.connect(b.g.destination);c=a.listenerPos;b.aa[0]=c[0];b.aa[1]=c[1];b.aa[2]=c[2];b.g.listener.setPosition(c[0],c[1],c[2]);b.g.listener.setOrientation(...b.fa);self.C3_GetAudioContextCurrentTime=()=>b.g.currentTime;try{await Promise.all(a.preloadList.map(d=>
O(b,d.originalUrl,d.url,d.type,!1)))}catch(d){console.error("[Construct] Preloading sounds failed: ",d)}return{sampleRate:b.g.sampleRate,audioContextState:b.g.state,outputLatency:b.g.outputLatency||0}}
async function sb(b,a){var c=a.originalUrl;const d=a.url,e=a.type,f=a.isMusic,g=a.tag,h=a.isLooping,k=a.vol,q=a.pos,p=a.panning,C=a.stereoPan;let z=a.off;0<z&&!a.trueClock&&(b.g.getOutputTimestamp?(a=b.g.getOutputTimestamp(),z=z-a.performanceTime/1E3+a.contextTime):z=z-performance.now()/1E3+b.g.currentTime);b.Md=g;tb(b,g);try{b.$=await ub(b,c,d,e,g,f);if(p){P(b.$,!0);var r=b.$,D=p.innerAngle,oa=p.outerAngle,pa=p.outerGain;if(r.qb){vb(r,p.x,p.y,p.z,p.angle);var G=self.eb.xe;r.ua[0]!==G(D)&&(r.ua[0]=
G(D),r.F.coneInnerAngle=G(D));r.ua[1]!==G(oa)&&(r.ua[1]=G(oa),r.F.coneOuterAngle=G(oa));r.ua[2]!==pa&&(r.ua[2]=pa,r.F.coneOuterGain=pa)}p.hasOwnProperty("uid")&&(b.$.sa=p.uid)}else"number"===typeof C&&0!==C?(Q(b.$,!0),wb(b.$,C)):(P(b.$,!1),Q(b.$,!1));b.$.Play(h,k,q,z)}catch(Ib){console.error("[Construct] Audio: error starting playback: ",Ib);return}finally{c=b.zb.get(g);if(!c)throw Error("expected pending tag");c.fd--;0===c.fd&&(c.resolve(),b.zb.delete(g))}u(b)}
async function xb(b,a){var c=a.tag;const d=a.vol,e=a.duration;a=a.stopOnEnd;await yb(b,c);for(const p of R(b,c)){c=p;var f=d,g=e,h=a;if(!c.Ta){var k=c.G.gain;k.cancelScheduledValues(0);var q=c.u.g.currentTime;g=q+g;k.setValueAtTime(k.value,q);k.linearRampToValueAtTime(f,g);c.Ka=f;c.Sa=g;c.Vd=h}}S(b)}async function zb(b,a){const c=a.tag;a=a.rate;await yb(b,c);for(const d of R(b,c))b=d,b.oa!==a&&(b.oa=a,b.Fa())}
async function Ab(b,a){const c=a.tag;a=a.pos;await yb(b,c);for(const d of R(b,c))d.uc(a)}async function Bb(b,a){const c=a.originalUrl,d=a.url,e=a.type;a=a.isMusic;try{await ub(b,c,d,e,"",a)}catch(f){console.error("[Construct] Audio: error preloading: ",f)}}async function Cb(b,a){if(a=await O(b,"",a.url,a.type,a.isMusic,!0))a.j(),a=b.ma.indexOf(a),-1!==a&&b.ma.splice(a,1)}
async function Db(b,a){var c=a.type,d=a.tag,e=a.params;if("filter"===c)e=new self.de(b,...e);else if("delay"===c)e=new self.be(b,...e);else if("convolution"===c){c=null;try{c=await O(b,a.bufferOriginalUrl,a.bufferUrl,a.bufferType,!1)}catch(g){console.log("[Construct] Audio: error loading convolution: ",g);return}c=e=new self.ae(b,c.la,...e);var f=a.bufferType;c.zd=a.bufferOriginalUrl;c.Ad=f}else if("flanger"===c)e=new self.ee(b,...e);else if("phaser"===c)e=new self.ge(b,...e);else if("gain"===c)e=
new self.fe(b,...e);else if("stereopan"===c)e=new self.ie(b,...e);else if("tremolo"===c)e=new self.je(b,...e);else if("ringmod"===c)e=new self.he(b,...e);else if("distortion"===c)e=new self.ce(b,...e);else if("compressor"===c)e=new self.$d(b,...e);else if("analyser"===c)e=new self.Zd(b,...e);else throw Error("invalid effect type");a=e;d=d.toLowerCase();e=b.na.get(d);e||(e=[],b.na.set(d,e));a.Jd=e.length;a.ha=d;e.push(a);Eb(b,d);Fb(b)}
async function Gb(b,a){const c=a.saveLoadMode;if(3!==c){var d=[];for(var e of b.J)e.Ca()&&1===c||!e.Ca()&&2===c?d.push(e):e.j();b.J=d}for(const f of b.na.values())for(const g of f)g.j();b.na.clear();b.ic=a.timeScale;b.Nc=a.gameTime;d=a.listenerPos;b.aa[0]=d[0];b.aa[1]=d[1];b.aa[2]=d[2];b.g.listener.setPosition(d[0],d[1],d[2]);d=a.listenerOrientation;if(Array.isArray(d)){for(e=0;6>e;++e)b.fa[e]=d[e];b.g.listener.setOrientation(...b.fa)}b.xa=a.isSilent;b.o.Ib(b.xa);b.Xb=a.masterVolume;b.Qa.gain.value=
b.Xb;d=[];for(const f of Object.values(a.effects))d.push(Promise.all(f.map(g=>Db(b,g))));await Promise.all(d);await Promise.all(a.playing.map(f=>Hb(b,f,c)));S(b)}
async function Jb(b,a){try{const c=b.g.suspend(a.time);b.Id?b.g.resume():(b.g.startRendering().then(d=>{const e=[];for(let f=0,g=d.numberOfChannels;f<g;++f){const h=d.getChannelData(f);e.push(h.buffer)}b.o.Gb("runtime","offline-audio-render-completed",{duration:d.duration,length:d.length,numberOfChannels:d.numberOfChannels,sampleRate:d.sampleRate,channelData:e},null,e)}).catch(d=>Kb(d)),b.Id=!0);await c}catch(c){Kb(c)}}
function rb(b){b.Rb||(b.Qc=!1,window.addEventListener("pointerup",b.Ba,!0),window.addEventListener("touchend",b.Ba,!0),window.addEventListener("click",b.Ba,!0),window.addEventListener("keydown",b.Ba,!0),b.Rb=!0)}
async function O(b,a,c,d,e,f){for(var g of b.ma)if(g.gb()===c)return await Lb(g),g;if(f)return null;if(e&&(b.bc||b.Hd)){f=0;for(let h=0,k=b.ma.length;h<k;++h)g=b.ma[h],b.ma[f]=g,g.Ca()?g.j():++f;b.ma.length=f}f="audio/webm; codecs=opus"===d&&!b.Wd;e&&f&&(b.Hd=!0);c=!e||b.bc||f?new self.me(b,a,c,d,e,f):new self.ke(b,a,c,d,e);b.ma.push(c);await Lb(c);b.Od.has(a)||(l(b,"buffer-metadata",{originalUrl:a,duration:c.ia()}),b.Od.add(a));return c}
function Mb(b,a){return(a=b.na.get(a.toLowerCase()))?a[0].N():b.pa()}function Eb(b,a){let c=b.pa();var d=b.na.get(a);if(d&&d.length){c=d[0].N();for(let f=0,g=d.length;f<g;++f){var e=d[f];f+1===g?e.S(b.pa()):e.S(d[f+1].N())}}for(const f of R(b,a))d=c,e=f.ga||f.F||f.G,e.disconnect(),e.connect(d);b.Ia&&b.Yc===a&&(b.Ia.disconnect(),b.Ia.connect(c))}
function*R(b,a){if(a)for(const c of b.J)b=c.ha,(b.length!==a.length?0:b===a||b.toLowerCase()===a.toLowerCase())&&(yield c);else b.$&&!b.$.U()&&(yield b.$)}function Nb(b,a,c){return c?b.o.Qe(a).then(d=>{const e=b.g.createBuffer(1,d.length,48E3);e.getChannelData(0).set(d);return e}):new Promise((d,e)=>{b.g.decodeAudioData(a,d,e)})}function Ob(b,a){let c=0;for(let d=0,e=b.J.length;d<e;++d){const f=b.J[d];b.J[c]=f;f.O===a?f.j():++c}b.J.length=c}
async function ub(b,a,c,d,e,f){for(const g of b.J)if(g.gb()===c&&(g.mc()||f))return g.ha=e,g;a=await O(b,a,c,d,f);e="html5"===a.Ic?new self.le(a.u,a,e):new self.ne(a.u,a,e);b.J.push(e);return e}function tb(b,a){let c=b.zb.get(a);if(!c){let d=null;c={fd:0,promise:new Promise(e=>d=e),resolve:d};b.zb.set(a,c)}c.fd++}function yb(b,a){a||(a=b.Md);return(b=b.zb.get(a))?b.promise:Promise.resolve()}function S(b){if(0<b.Pa.size)u(b);else for(const a of b.J)if(!a.I&&!a.U()){u(b);break}}
function Pb(b,a,c,d){l(b,"trigger",{type:a,tag:c,aiid:d})}function Fb(b){b.Tc||(b.Tc=!0,Promise.resolve().then(()=>Qb(b)))}function Qb(b){const a={};for(const [c,d]of b.na)a[c]=d.map(e=>e.fb());l(b,"fxstate",{fxstate:a});b.Tc=!1}
async function Hb(b,a,c){if(3!==c){var d=a.bufferOriginalUrl,e=a.bufferUrl,f=a.bufferType,g=a.isMusic,h=a.tag,k=a.isLooping,q=a.volume,p=a.playbackTime;if(!g||1!==c)if(g||2!==c){c=null;try{c=await ub(b,d,e,f,h,g)}catch(C){console.error("[Construct] Audio: error loading audio state: ",C);return}b=c;(d=a.pan)?(P(b,!0),e=b.F,f=d.pos,b.Xa[0]=f[0],b.Xa[1]=f[1],b.Xa[2]=f[2],f=d.orient,b.Wa[0]=f[0],b.Wa[1]=f[1],b.Wa[2]=f[2],e.setPosition(...b.Xa),e.setOrientation(...b.Wa),b.ua[0]=d.cia,b.ua[1]=d.coa,b.ua[2]=
d.cog,e.coneInnerAngle=d.cia,e.coneOuterAngle=d.coa,e.coneOuterGain=d.cog,b.sa=d.uid):P(b,!1);b=c;d=a.stereoPan;"number"!==typeof d?Q(b,!1):(Q(b,!0),wb(b,d));c.Play(k,q,p,0);a.isPlaying||c.ib();c.Bc(a)}}}function Kb(b){console.error("[Audio] Offline rendering error: ",b)}
self.eb=class extends self.Ma{constructor(b){super(b,"audio");this.Qa=this.g=null;this.Rb=this.Qc=!1;this.Ba=()=>{if(!this.Qc){var a=this.g;"suspended"===a.state&&a.resume&&a.resume();var c=a.createBuffer(1,220,22050),d=a.createBufferSource();d.buffer=c;d.connect(a.destination);d.start(0);"running"===a.state&&this.Rb&&(this.Qc=!0,window.removeEventListener("pointerup",this.Ba,!0),window.removeEventListener("touchend",this.Ba,!0),window.removeEventListener("click",this.Ba,!0),window.removeEventListener("keydown",
this.Ba,!0),this.Rb=!1)}};this.ma=[];this.J=[];this.$=null;this.Md="";this.Od=new Set;this.Nd=-1;this.zb=new Map;this.Xb=1;this.xa=!1;this.cd=0;this.ic=1;this.Nc=0;this.Qd="HRTF";this.Bd="inverse";this.Rd=600;this.Pd=1E4;this.Td=1;this.aa=[0,0,0];this.fa=[0,0,-1,0,1,0];this.Hd=this.bc=!1;this.Wd=this.o.se();this.na=new Map;this.Pa=new Set;this.Id=this.Tc=!1;this.Yc="";this.Ia=null;self.C3Audio_OnMicrophoneStream=(a,c)=>{this.Ia&&this.Ia.disconnect();this.Yc=c.toLowerCase();this.Ia=this.g.createMediaStreamSource(a);
this.Ia.connect(Mb(this,this.Yc))};this.Ob=null;self.C3Audio_GetOutputStream=()=>{this.Ob||(this.Ob=this.g.createMediaStreamDestination(),this.Qa.connect(this.Ob));return this.Ob.stream};self.C3Audio_DOMInterface=this;t(this,[["create-audio-context",a=>qb(this,a)],["play",a=>sb(this,a)],["stop",a=>{a=a.tag;for(const c of R(this,a))c.Da()}],["stop-all",()=>{for(const a of this.J)a.Da()}],["set-paused",a=>{const c=a.tag;a=a.paused;for(const d of R(this,c))a?d.ib():d.Hb();S(this)}],["set-volume",a=>
{const c=a.tag;a=a.vol;for(const d of R(this,c))T(d,a)}],["fade-volume",a=>xb(this,a)],["set-master-volume",a=>{this.Xb=a.vol;this.Qa.gain.value=this.Xb}],["set-muted",a=>{const c=a.tag;a=a.isMuted;for(const d of R(this,c))Rb(d,a)}],["set-silent",a=>{this.xa=a.isSilent;this.o.Ib(this.xa);for(const c of this.J)c.Mb()}],["set-looping",a=>{const c=a.tag;a=a.isLooping;for(const d of R(this,c))d.vc(a)}],["set-playback-rate",a=>zb(this,a)],["set-stereo-pan",a=>{const c=a.tag;a=a.p;for(const d of R(this,
c))Q(d,!0),wb(d,a)}],["seek",a=>Ab(this,a)],["preload",a=>Bb(this,a)],["unload",a=>Cb(this,a)],["unload-all",()=>{for(const a of this.ma)a.j();this.ma.length=0}],["set-suspended",a=>{a=a.isSuspended;!a&&this.g.resume&&this.g.resume();for(const c of this.J)c.wc(a);a&&this.g.suspend&&this.g.suspend()}],["add-effect",a=>Db(this,a)],["set-effect-param",a=>{const c=a.index,d=a.param,e=a.value,f=a.ramp,g=a.time;a=this.na.get(a.tag);!a||0>c||c>=a.length||(a[c].Y(d,e,f,g),Fb(this))}],["remove-effects",a=>
{a=a.tag.toLowerCase();const c=this.na.get(a);if(c&&c.length){for(const d of c)d.j();this.na.delete(a);Eb(this,a)}}],["tick",a=>{this.ic=a.timeScale;this.Nc=a.gameTime;this.Nd=a.tickCount;if(0!==this.cd)for(var c of this.J)c.Fa();!(c=a.listenerPos)||this.aa[0]===c[0]&&this.aa[1]===c[1]&&this.aa[2]===c[2]||(this.aa[0]=c[0],this.aa[1]=c[1],this.aa[2]=c[2],this.g.listener.setPosition(c[0],c[1],c[2]));if((c=a.listenerOrientation)&&(this.fa[0]!==c[0]||this.fa[1]!==c[1]||this.fa[2]!==c[2]||this.fa[3]!==
c[3]||this.fa[4]!==c[4]||this.fa[5]!==c[5])){for(let d=0;6>d;++d)this.fa[d]=c[d];this.g.listener.setOrientation(...this.fa)}for(const d of a.instPans){a=d.uid;for(const e of this.J)e.sa===a&&vb(e,d.x,d.y,d.z,d.angle)}}],["load-state",a=>Gb(this,a)],["offline-render-audio",a=>Jb(this,a)],["offline-render-finish",()=>{this.g.resume()}]])}V(){return this.g}pa(){return this.Qa}Fb(){return this.xa}ea(b){this.o.ea(b)}ja(b){this.o.ja(b)}Ea(){for(var b of this.Pa)b.Ea();b=this.g.currentTime;for(var a of this.J)a.Ea(b);
a=this.J.filter(c=>!c.I&&!c.U()).map(c=>c.fb());l(this,"state",{tickCount:this.Nd,outputLatency:this.g.outputLatency||0,audioInstances:a,analysers:[...this.Pa].map(c=>({tag:c.ha,index:c.Jd,peak:c.Ya,rms:c.Sd,binCount:c.l.frequencyBinCount,freqBins:c.Gd}))});0===a.length&&0===this.Pa.size&&aa(this)}static xe(b){return b*pb}static md(b){return Math.max(Math.min(Math.pow(10,b/20),1),0)}static ve(b){return Math.log(Math.max(Math.min(b,1),0))/Math.log(10)*20}};self.qa.La(self.eb);"use strict";
function Lb(b){b.Vb||(b.Vb=b.Ac());return b.Vb}self.hd=class{constructor(b,a,c,d,e){this.u=b;this.Ve=a;this.Ja=c;this.R=d;this.Se=e;this.Ic="";this.Vb=null}j(){this.Vb=this.u=null}Ac(){}V(){return this.u.V()}pc(){return this.Ve}gb(){return this.Ja}oc(){return this.R}Ca(){return this.Se}ia(){}};"use strict";
self.ke=class extends self.hd{constructor(b,a,c,d,e){super(b,a,c,d,e);this.Ic="html5";this.M=new Audio;this.M.crossOrigin="anonymous";this.M.autoplay=!1;this.M.preload="auto";this.tb=this.ub=null;this.M.addEventListener("canplaythrough",()=>!0);this.yb=this.V().createGain();this.wb=null;this.M.addEventListener("canplay",()=>{this.ub&&(this.ub(),this.tb=this.ub=null);!this.wb&&this.M&&(this.wb=this.V().createMediaElementSource(this.M),this.wb.connect(this.yb))});this.onended=null;this.M.addEventListener("ended",
()=>{if(this.onended)this.onended()});this.M.addEventListener("error",f=>{console.error(`[Construct] Audio '${this.Ja}' error: `,f);this.tb&&(this.tb(f),this.tb=this.ub=null)})}j(){Ob(this.u,this);this.yb.disconnect();this.yb=null;this.wb.disconnect();this.wb=null;this.M&&!this.M.paused&&this.M.pause();this.M=this.onended=null;super.j()}Ac(){return new Promise((b,a)=>{this.ub=b;this.tb=a;this.M.src=this.Ja})}T(){return this.M}ia(){return this.M.duration}};"use strict";
async function Sb(b){if(b.Ga)return b.Ga;var a=b.u.o;if("cordova"===a.v&&a.od(b.Ja)&&a.Tb)b.Ga=await a.Eb(b.Ja);else{a=await fetch(b.Ja);if(!a.ok)throw Error(`error fetching audio data: ${a.status} ${a.statusText}`);b.Ga=await a.arrayBuffer()}}async function Tb(b){if(b.la)return b.la;b.la=await Nb(b.u,b.Ga,b.Ue);b.Ga=null}
self.me=class extends self.hd{constructor(b,a,c,d,e,f){super(b,a,c,d,e);this.Ic="webaudio";this.la=this.Ga=null;this.Ue=!!f}j(){Ob(this.u,this);this.la=this.Ga=null;super.j()}async Ac(){try{await Sb(this),await Tb(this)}catch(b){console.error(`[Construct] Failed to load audio '${this.Ja}': `,b)}}ia(){return this.la?this.la.duration:0}};"use strict";let Ub=0;
function P(b,a){a=!!a;b.qb!==a&&(b.qb=a,b.qb?(Q(b,!1),b.F||(b.F=b.V().createPanner(),b.F.panningModel=b.u.Qd,b.F.distanceModel=b.u.Bd,b.F.refDistance=b.u.Rd,b.F.maxDistance=b.u.Pd,b.F.rolloffFactor=b.u.Td),b.G.disconnect(),b.G.connect(b.F),b.F.connect(b.pa())):(b.F.disconnect(),b.G.disconnect(),b.G.connect(b.pa())))}
function Q(b,a){a=!!a;b.Ub!==a&&(b.Ub=a,b.Ub?(P(b,!1),b.ga=b.V().createStereoPanner(),b.G.disconnect(),b.G.connect(b.ga),b.ga.connect(b.pa())):(b.ga.disconnect(),b.ga=null,b.G.disconnect(),b.G.connect(b.pa())))}function wb(b,a){b.Ub&&b.ad!==a&&(b.ga.pan.value=a,b.ad=a)}function T(b,a){b.Ka=a;b.G.gain.cancelScheduledValues(0);b.Sa=-1;b.G.gain.value=b.qc()}function Rb(b,a){a=!!a;b.Ta!==a&&(b.Ta=a,b.Mb())}
function vb(b,a,c,d,e){if(b.qb){var f=b.Xa,g=b.Wa,h=Math.cos(e);e=Math.sin(e);if(f[0]!==a||f[1]!==c||f[2]!==d)f[0]=a,f[1]=c,f[2]=d,b.F.setPosition(...f);if(g[0]!==h||g[1]!==e||0!==g[2])g[0]=h,g[1]=e,g[2]=0,b.F.setOrientation(...g)}}function U(b){return b.Vc?b.u.Nc:performance.now()/1E3}
self.jd=class{constructor(b,a,c){this.u=b;this.O=a;this.ha=c;this.Nb=Ub++;this.G=this.V().createGain();this.G.connect(this.pa());this.F=null;this.qb=!1;this.Xa=[0,0,0];this.Wa=[0,0,0];this.ua=[0,0,0];this.ga=null;this.Ub=!1;this.ad=0;this.I=!0;this.X=this.va=this.K=!1;this.Ka=1;this.Ta=!1;this.oa=1;b=this.u.cd;this.Vc=1===b&&!this.Ca()||2===b;this.Sa=this.sa=-1;this.Vd=!1}j(){this.O=this.u=null;this.F&&(this.F.disconnect(),this.F=null);this.ga&&(this.ga.disconnect(),this.ga=null);this.G.disconnect();
this.G=null}V(){return this.u.V()}pa(){return Mb(this.u,this.ha)}pc(){return this.O.pc()}gb(){return this.O.gb()}oc(){return this.O.oc()}Ca(){return this.O.Ca()}U(){}mc(){}IsPlaying(){return!this.I&&!this.K&&!this.U()}Na(){}ia(){return this.O.ia()}Play(){}Da(){}ib(){}Hb(){}Ea(b){-1!==this.Sa&&b>=this.Sa&&(this.Sa=-1,this.Vd&&this.Da(),Pb(this.u,"fade-ended",this.ha,this.Nb))}qc(){const b=this.Ka;return isFinite(b)?b:0}Fb(){return this.u.Fb()}Mb(){}vc(){}Fa(){}uc(){}wc(){}rc(){}fb(){var b=this.Nb,
a=this.ha,c=this.ia(),d=-1===this.Sa?this.Ka:this.G.gain.value,e=this.IsPlaying();if(this.F){var f=this.F;f={pos:this.Xa,orient:this.Wa,cia:f.coneInnerAngle,coa:f.coneOuterAngle,cog:f.coneOuterGain,uid:this.sa}}else f=null;return{aiid:b,tag:a,duration:c,volume:d,isPlaying:e,playbackTime:this.Na(),playbackRate:this.oa,uid:this.sa,bufferOriginalUrl:this.pc(),bufferUrl:"",bufferType:this.oc(),isMusic:this.Ca(),isLooping:this.X,isMuted:this.Ta,resumePosition:this.rc(),pan:f,stereoPan:this.ga?this.ad:
null}}Bc(b){var a=b.playbackRate;this.oa!==a&&(this.oa=a,this.Fa());Rb(this,b.isMuted)}};"use strict";
self.le=class extends self.jd{constructor(b,a,c){super(b,a,c);this.O.yb.connect(this.G);this.O.onended=()=>this.Dc()}j(){this.Da();this.O.yb.disconnect();super.j()}T(){return this.O.T()}Dc(){this.I=!0;this.sa=-1;Pb(this.u,"ended",this.ha,this.Nb)}U(){return this.T().ended}mc(){return this.I?!0:this.U()}Na(){let b=this.T().currentTime;this.X||(b=Math.min(b,this.ia()));return b}Play(b,a,c){const d=this.T();1!==d.playbackRate&&(d.playbackRate=1);d.loop!==b&&(d.loop=b);T(this,a);d.muted&&(d.muted=!1);
if(d.currentTime!==c)try{d.currentTime=c}catch(e){console.warn(`[Construct] Exception seeking audio '${this.O.gb()}' to position '${c}': `,e)}this.u.ea(d);this.K=this.I=!1;this.X=b;this.oa=1}Da(){const b=this.T();b.paused||b.pause();this.u.ja(b);this.I=!0;this.K=!1;this.sa=-1}ib(){if(!(this.K||this.I||this.U())){var b=this.T();b.paused||b.pause();this.u.ja(b);this.K=!0}}Hb(){!this.K||this.I||this.U()||(this.u.ea(this.T()),this.K=!1)}Mb(){this.T().muted=this.Ta||this.Fb()}vc(b){b=!!b;this.X!==b&&(this.X=
b,this.T().loop=b)}Fa(){let b=this.oa;this.Vc&&(b*=this.u.ic);try{this.T().playbackRate=b}catch(a){console.warn(`[Construct] Unable to set playback rate '${b}':`,a)}}uc(b){if(!this.I&&!this.U())try{this.T().currentTime=b}catch(a){console.warn(`[Construct] Error seeking audio to '${b}': `,a)}}rc(){return this.Na()}wc(b){b?this.IsPlaying()?(this.T().pause(),this.va=!0):this.va=!1:this.va&&(this.u.ea(this.T()),this.va=!1)}};"use strict";function V(b){b.s&&b.s.disconnect();b.s=null;b.jb=null}
self.ne=class extends self.jd{constructor(b,a,c){super(b,a,c);this.s=null;this.$b=d=>this.Dc(d);this.Pc=!0;this.jb=null;this.P=this.ac=this.cc=0;this.Zc=1}j(){this.Da();V(this);this.$b=null;super.j()}Dc(b){this.K||this.va||b.target!==this.jb||(this.I=this.Pc=!0,this.sa=-1,V(this),Pb(this.u,"ended",this.ha,this.Nb))}U(){return!this.I&&this.s&&this.s.loop||this.K?!1:this.Pc}mc(){return!this.s||this.I?!0:this.U()}Na(){let b;b=this.K?this.P:this.ac+(U(this)-this.cc)*this.oa;this.X||(b=Math.min(b,this.ia()));
return b}Play(b,a,c,d){this.Zc=1;T(this,a);V(this);this.s=this.V().createBufferSource();this.s.buffer=this.O.la;this.s.connect(this.G);this.jb=this.s;this.s.onended=this.$b;this.s.loop=b;this.s.start(d,c);this.K=this.I=this.Pc=!1;this.X=b;this.oa=1;this.cc=U(this);this.ac=c}Da(){if(this.s)try{this.s.stop(0)}catch(b){}this.I=!0;this.K=!1;this.sa=-1}ib(){this.K||this.I||this.U()||(this.P=this.Na(),this.X&&(this.P%=this.ia()),this.K=!0,this.s.stop(0))}Hb(){!this.K||this.I||this.U()||(V(this),this.s=
this.V().createBufferSource(),this.s.buffer=this.O.la,this.s.connect(this.G),this.jb=this.s,this.s.onended=this.$b,this.s.loop=this.X,T(this,this.Ka),this.Fa(),this.s.start(0,this.P),this.cc=U(this),this.ac=this.P,this.K=!1)}qc(){return super.qc()*this.Zc}Mb(){this.Zc=this.Ta||this.Fb()?0:1;T(this,this.Ka)}vc(b){b=!!b;this.X!==b&&(this.X=b,this.s&&(this.s.loop=b))}Fa(){let b=this.oa;this.Vc&&(b*=this.u.ic);this.s&&(this.s.playbackRate.value=b)}uc(b){this.I||this.U()||(this.K?this.P=b:(this.ib(),this.P=
b,this.Hb()))}rc(){return this.P}wc(b){b?this.IsPlaying()?(this.va=!0,this.P=this.Na(),this.X&&(this.P%=this.ia()),this.s.stop(0)):this.va=!1:this.va&&(V(this),this.s=this.V().createBufferSource(),this.s.buffer=this.O.la,this.s.connect(this.G),this.jb=this.s,this.s.onended=this.$b,this.s.loop=this.X,T(this,this.Ka),this.Fa(),this.s.start(0,this.P),this.cc=U(this),this.ac=this.P,this.va=!1)}Bc(b){super.Bc(b);this.P=b.resumePosition}};"use strict";function W(b){return b.g.createGain()}
function X(b,a,c,d,e){a.cancelScheduledValues(0);if(0===e)a.value=c;else switch(b=b.g.currentTime,e+=b,d){case 0:a.setValueAtTime(c,e);break;case 1:a.setValueAtTime(a.value,b);a.linearRampToValueAtTime(c,e);break;case 2:a.setValueAtTime(a.value,b),a.exponentialRampToValueAtTime(c,e)}}class Y{constructor(b){this.u=b;this.g=b.V();this.Jd=-1;this.R=this.ha="";this.m=null}j(){this.g=null}N(){}S(){}fb(){return{type:this.R,tag:this.ha,params:this.m}}}
self.de=class extends Y{constructor(b,a,c,d,e,f,g){super(b);this.R="filter";this.m=[a,c,d,e,f,g];this.A=W(this);this.i=W(this);this.i.gain.value=g;this.h=W(this);this.h.gain.value=1-g;this.D=this.g.createBiquadFilter();this.D.type=a;this.D.frequency.value=c;this.D.detune.value=d;this.D.Q.value=e;this.D.gain.vlaue=f;this.A.connect(this.D);this.A.connect(this.h);this.D.connect(this.i)}j(){this.A.disconnect();this.D.disconnect();this.i.disconnect();this.h.disconnect();super.j()}S(b){this.i.disconnect();
this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.A}Y(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.m[5]=a;X(this,this.i.gain,a,c,d);X(this,this.h.gain,1-a,c,d);break;case 1:this.m[1]=a;X(this,this.D.frequency,a,c,d);break;case 2:this.m[2]=a;X(this,this.D.detune,a,c,d);break;case 3:this.m[3]=a;X(this,this.D.Q,a,c,d);break;case 4:this.m[4]=a,X(this,this.D.gain,a,c,d)}}};
self.be=class extends Y{constructor(b,a,c,d){super(b);this.R="delay";this.m=[a,c,d];this.A=W(this);this.i=W(this);this.i.gain.value=d;this.h=W(this);this.h.gain.value=1-d;this.vb=W(this);this.W=this.g.createDelay(a);this.W.delayTime.value=a;this.ob=W(this);this.ob.gain.value=c;this.A.connect(this.vb);this.A.connect(this.h);this.vb.connect(this.i);this.vb.connect(this.W);this.W.connect(this.ob);this.ob.connect(this.vb)}j(){this.A.disconnect();this.i.disconnect();this.h.disconnect();this.vb.disconnect();
this.W.disconnect();this.ob.disconnect();super.j()}S(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.A}Y(b,a,c,d){const e=self.eb.md;switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.m[2]=a;X(this,this.i.gain,a,c,d);X(this,this.h.gain,1-a,c,d);break;case 4:this.m[1]=e(a);X(this,this.ob.gain,e(a),c,d);break;case 5:this.m[0]=a,X(this,this.W.delayTime,a,c,d)}}};
self.ae=class extends Y{constructor(b,a,c,d){super(b);this.R="convolution";this.m=[c,d];this.Ad=this.zd="";this.A=W(this);this.i=W(this);this.i.gain.value=d;this.h=W(this);this.h.gain.value=1-d;this.nb=this.g.createConvolver();this.nb.normalize=c;this.nb.buffer=a;this.A.connect(this.nb);this.A.connect(this.h);this.nb.connect(this.i)}j(){this.A.disconnect();this.nb.disconnect();this.i.disconnect();this.h.disconnect();super.j()}S(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.A}Y(b,
a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0),this.m[1]=a,X(this,this.i.gain,a,c,d),X(this,this.h.gain,1-a,c,d)}}fb(){const b=super.fb();b.bufferOriginalUrl=this.zd;b.bufferUrl="";b.bufferType=this.Ad;return b}};
self.ee=class extends Y{constructor(b,a,c,d,e,f){super(b);this.R="flanger";this.m=[a,c,d,e,f];this.A=W(this);this.h=W(this);this.h.gain.value=1-f/2;this.i=W(this);this.i.gain.value=f/2;this.pb=W(this);this.pb.gain.value=e;this.W=this.g.createDelay(a+c);this.W.delayTime.value=a;this.B=this.g.createOscillator();this.B.frequency.value=d;this.L=W(this);this.L.gain.value=c;this.A.connect(this.W);this.A.connect(this.h);this.W.connect(this.i);this.W.connect(this.pb);this.pb.connect(this.W);this.B.connect(this.L);
this.L.connect(this.W.delayTime);this.B.start(0)}j(){this.B.stop(0);this.A.disconnect();this.W.disconnect();this.B.disconnect();this.L.disconnect();this.h.disconnect();this.i.disconnect();this.pb.disconnect();super.j()}S(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.A}Y(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.m[4]=a;X(this,this.i.gain,a/2,c,d);X(this,this.h.gain,1-a/2,c,d);break;case 6:this.m[1]=a/1E3;X(this,this.L.gain,a/1E3,
c,d);break;case 7:this.m[2]=a;X(this,this.B.frequency,a,c,d);break;case 8:this.m[3]=a/100,X(this,this.pb.gain,a/100,c,d)}}};
self.ge=class extends Y{constructor(b,a,c,d,e,f,g){super(b);this.R="phaser";this.m=[a,c,d,e,f,g];this.A=W(this);this.h=W(this);this.h.gain.value=1-g/2;this.i=W(this);this.i.gain.value=g/2;this.D=this.g.createBiquadFilter();this.D.type="allpass";this.D.frequency.value=a;this.D.detune.value=c;this.D.Q.value=d;this.B=this.g.createOscillator();this.B.frequency.value=f;this.L=W(this);this.L.gain.value=e;this.A.connect(this.D);this.A.connect(this.h);this.D.connect(this.i);this.B.connect(this.L);this.L.connect(this.D.frequency);
this.B.start(0)}j(){this.B.stop(0);this.A.disconnect();this.D.disconnect();this.B.disconnect();this.L.disconnect();this.h.disconnect();this.i.disconnect();super.j()}S(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.A}Y(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.m[5]=a;X(this,this.i.gain,a/2,c,d);X(this,this.h.gain,1-a/2,c,d);break;case 1:this.m[0]=a;X(this,this.D.frequency,a,c,d);break;case 2:this.m[1]=a;X(this,this.D.detune,a,c,d);
break;case 3:this.m[2]=a;X(this,this.D.Q,a,c,d);break;case 6:this.m[3]=a;X(this,this.L.gain,a,c,d);break;case 7:this.m[4]=a,X(this,this.B.frequency,a,c,d)}}};self.fe=class extends Y{constructor(b,a){super(b);this.R="gain";this.m=[a];this.l=W(this);this.l.gain.value=a}j(){this.l.disconnect();super.j()}S(b){this.l.disconnect();this.l.connect(b)}N(){return this.l}Y(b,a,c,d){const e=self.eb.md;switch(b){case 4:this.m[0]=e(a),X(this,this.l.gain,e(a),c,d)}}};
self.ie=class extends Y{constructor(b,a){super(b);this.R="stereopan";this.m=[a];this.l=this.g.createStereoPanner();this.l.pan.value=a}j(){this.l.disconnect();super.j()}S(b){this.l.disconnect();this.l.connect(b)}N(){return this.l}Y(b,a,c,d){a=Math.min(Math.max(a/100,-1),1);switch(b){case 9:this.m[0]=a,X(this,this.l.pan,a,c,d)}}};
self.je=class extends Y{constructor(b,a,c){super(b);this.R="tremolo";this.m=[a,c];this.l=W(this);this.l.gain.value=1-c/2;this.B=this.g.createOscillator();this.B.frequency.value=a;this.L=W(this);this.L.gain.value=c/2;this.B.connect(this.L);this.L.connect(this.l.gain);this.B.start(0)}j(){this.B.stop(0);this.B.disconnect();this.L.disconnect();this.l.disconnect();super.j()}S(b){this.l.disconnect();this.l.connect(b)}N(){return this.l}Y(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.m[1]=
a;X(this,this.l.gain,1-a/2,c,d);X(this,this.L.gain,a/2,c,d);break;case 7:this.m[0]=a,X(this,this.B.frequency,a,c,d)}}};
self.he=class extends Y{constructor(b,a,c){super(b);this.R="ringmod";this.m=[a,c];this.A=W(this);this.i=W(this);this.i.gain.value=c;this.h=W(this);this.h.gain.value=1-c;this.Bb=W(this);this.Bb.gain.value=0;this.B=this.g.createOscillator();this.B.frequency.value=a;this.B.connect(this.Bb.gain);this.B.start(0);this.A.connect(this.Bb);this.A.connect(this.h);this.Bb.connect(this.i)}j(){this.B.stop(0);this.B.disconnect();this.Bb.disconnect();this.A.disconnect();this.i.disconnect();this.h.disconnect();super.j()}S(b){this.i.disconnect();
this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.A}Y(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.m[1]=a;X(this,this.i.gain,a,c,d);X(this,this.h.gain,1-a,c,d);break;case 7:this.m[0]=a,X(this,this.B.frequency,a,c,d)}}};
self.ce=class extends Y{constructor(b,a,c,d,e,f){super(b);this.R="distortion";this.m=[a,c,d,e,f];this.A=W(this);this.ec=W(this);this.dc=W(this);b=d;.01>b&&(b=.01);this.ec.gain.value=b;this.dc.gain.value=Math.pow(1/b,.6)*e;this.i=W(this);this.i.gain.value=f;this.h=W(this);this.h.gain.value=1-f;this.jc=this.g.createWaveShaper();this.Jc=new Float32Array(65536);for(e=0;32768>e;++e)f=e/32768,b=1.05*c*a-a,d=0>f?-f:f,d<a?b=d:(d=1-Math.exp(-(1/b)*(d-a)),b=a+b*d),f=b*(0>f?-1:1),this.Jc[32768+e]=f,this.Jc[32768-
e-1]=-f;this.jc.curve=this.Jc;this.A.connect(this.ec);this.A.connect(this.h);this.ec.connect(this.jc);this.jc.connect(this.dc);this.dc.connect(this.i)}j(){this.A.disconnect();this.ec.disconnect();this.jc.disconnect();this.dc.disconnect();this.i.disconnect();this.h.disconnect();super.j()}S(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.A}Y(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0),this.m[4]=a,X(this,this.i.gain,a,c,d),X(this,this.h.gain,
1-a,c,d)}}};self.$d=class extends Y{constructor(b,a,c,d,e,f){super(b);this.R="compressor";this.m=[a,c,d,e,f];this.l=this.g.createDynamicsCompressor();this.l.threshold.value=a;this.l.knee.value=c;this.l.ratio.value=d;this.l.attack.value=e;this.l.release.value=f}j(){this.l.disconnect();super.j()}S(b){this.l.disconnect();this.l.connect(b)}N(){return this.l}Y(){}};
self.Zd=class extends Y{constructor(b,a,c){super(b);this.R="analyser";this.m=[a,c];this.l=this.g.createAnalyser();this.l.fftSize=a;this.l.smoothingTimeConstant=c;this.Gd=new Float32Array(this.l.frequencyBinCount);this.Ud=new Uint8Array(a);this.Sd=this.Ya=0;b=this.u;b.Pa.add(this);S(b)}j(){this.u.Pa.delete(this);this.l.disconnect();super.j()}Ea(){this.l.getFloatFrequencyData(this.Gd);this.l.getByteTimeDomainData(this.Ud);const b=this.l.fftSize;let a=this.Ya=0;for(var c=0;c<b;++c){let d=(this.Ud[c]-
128)/128;0>d&&(d=-d);this.Ya<d&&(this.Ya=d);a+=d*d}c=self.eb.ve;this.Ya=c(this.Ya);this.Sd=c(Math.sqrt(a/b))}S(b){this.l.disconnect();this.l.connect(b)}N(){return this.l}Y(){}};"use strict";
async function Vb(b,a){b.Uc=a.isInWorker;a=document.createElement("video");b.hc=!!a.requestVideoFrameCallback&&!b.o.sc();const c=!!self.createImageBitmap;b.Ab=b.Uc||c;return{postImageBitmaps:b.Ab,supportedFormats:{"video/webm":!!a.canPlayType("video/webm"),"video/ogg":!!a.canPlayType("video/ogg"),"video/mp4":!!a.canPlayType("video/mp4")}}}
async function Wb(b,a){if(!b.Kc.has(a)){a.c3_rvfcId=a.requestVideoFrameCallback(()=>Wb(b,a));try{const c=a.c3_sequenceNumber++,d=await createImageBitmap(a);c>a.c3_lastFrameSequence&&(a.c3_imageBitmap=d,a.c3_lastFrameSequence=c)}catch(c){}}}function Z(b,a,c,d){b.Kc.has(a)||v(b,"playback-event",c,{type:d})}
self.qa.La(class extends self.pe{constructor(b){super(b);this.Ab=this.hc=this.Uc=this.kb=!1;this.Zb=this.Xe=0;this.Kc=new WeakSet;n(this,"init",a=>Vb(this,a));w(this,"play",a=>{this.ea(a)});w(this,"pause",a=>{this.ja(a);a.pause()});w(this,"set-source",(a,c)=>{a.src=c.src;a.load()});w(this,"set-playback-time",(a,c)=>{try{a.currentTime=c.time}catch(d){console.error("[Video] Exception setting playback time: ",d)}});w(this,"set-playback-rate",(a,c)=>{try{a.playbackRate=c.rate}catch(d){console.error("[Video] Exception setting playback rate: ",
d)}});w(this,"set-looping",(a,c)=>{a.loop=c.isLooping});w(this,"set-muted",(a,c)=>{a.muted=c.isMuted});w(this,"set-volume",(a,c)=>{a.volume=c.volume});self.C3Video_GetElement=a=>x(this,a)}ea(b){this.o.ea(b);this.Ab&&this.hc&&-1===b.c3_rvfcId&&(b.c3_rvfcId=b.requestVideoFrameCallback(()=>Wb(this,b)))}ja(b){this.o.ja(b);this.Ab&&this.hc&&-1!==b.c3_rvfcId&&(b.cancelVideoFrameCallback(b.c3_rvfcId),b.c3_rvfcId=-1)}ld(b,a){const c=document.createElement("video");c.crossOrigin="anonymous";c.playsInline=
!0;c.c3_imageBitmap=null;c.c3_rvfcId=-1;c.c3_sequenceNumber=0;c.c3_lastFrameSequence=-1;c.addEventListener("canplay",()=>Z(this,c,b,0));c.addEventListener("canplaythrough",()=>Z(this,c,b,1));c.addEventListener("ended",()=>Z(this,c,b,2));c.addEventListener("error",()=>Z(this,c,b,3));c.addEventListener("loadstart",()=>Z(this,c,b,4));c.addEventListener("playing",()=>Z(this,c,b,5));c.addEventListener("pause",()=>Z(this,c,b,6));c.addEventListener("stalled",()=>Z(this,c,b,7));const d=a.autoplay;0===d?(c.autoplay=
!1,c.preload="none"):1===d?(c.autoplay=!1,c.preload="auto"):c.autoplay=!0;a.src&&(c.src=a.src);2===d&&this.ea(c);this.Zb++;u(this);return c}qd(){}nd(b){this.ja(b);b&&!b.paused&&!b.ended&&0<b.currentTime&&b.pause();b.src="";this.Zb=Math.max(this.Zb-1,0);0===this.Zb&&aa(this);this.Kc.add(b)}Ea(){const b={},a={sequenceNumber:this.Xe++,videoData:b},c=[],d=[];for(const [e,f]of this.Ra.entries()){const g=f.Qb,h={currentTime:g.currentTime,playbackRate:g.playbackRate,duration:g.duration,videoWidth:g.videoWidth,
videoHeight:g.videoHeight};if(this.Ab)if(this.hc){const k=g.c3_imageBitmap;g.c3_imageBitmap=null;(h.imageBitmap=k)&&c.push(k)}else d.push(createImageBitmap(g).then(k=>{h.imageBitmap=k;c.push(k)}).catch(()=>{h.imageBitmap=null}));b[e.toString()]=h}Promise.all(d).then(()=>{this.Uc?l(this,"state",a,!1,c):m(this,"state",a)})}});
